version: '3.8'
services: 
  dev-db:
    image: postgres:16
    ports:
     - 5434:5432
    environment:
      POSTGRES_USER: postgres_cooksoo
      POSTGRES_PASSWORD: Jorik
      POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp: 
      